ALTER TABLE `promo_code` ADD `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `status`;
ALTER TABLE `promo_code` ADD `ip` VARCHAR(24) NULL AFTER `date`;
ALTER TABLE `promo_code` DROP INDEX `PRIMARY`;
ALTER TABLE `promo_code` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);
